// Swift reserved words that need backtick-escaping when used as identifiers.
const SWIFT_KEYWORDS = new Set([
    // Declarations
    "associatedtype", "class", "deinit", "enum", "extension", "fileprivate",
    "func", "import", "init", "inout", "internal", "let", "open", "operator",
    "precedencegroup", "private", "protocol", "public", "rethrows", "static",
    "struct", "subscript", "typealias", "var",
    // Statements
    "break", "case", "catch", "continue", "default", "defer", "do", "else",
    "fallthrough", "for", "guard", "if", "in", "repeat", "return", "switch",
    "throw", "where", "while",
    // Expressions / types
    "Any", "as", "await", "false", "is", "nil", "self", "Self", "super",
    "throws", "true", "try",
    // Contextual keywords (Swift 5.7+)
    "some", "any",
]);

/** Wrap a Swift keyword in backticks so it can be used as an identifier. */
export function swiftEscapeKeyword(name: string): string {
    return SWIFT_KEYWORDS.has(name) ? `\`${name}\`` : name;
}

export function swiftHeader(): string {
    return [
        "// Generated by native/scripts/codegen — DO NOT EDIT BY HAND.",
        "// Source of truth: packages/shared. Regenerate via `bun native/scripts/codegen/generate.ts`.",
        "",
        "",
    ].join("\n");
}

export function pascalCase(s: string): string {
    return s
        .split(/[:_\-\s]+/)
        .filter(Boolean)
        .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
        .join("");
}

export function camelCase(s: string): string {
    const p = pascalCase(s);
    return p.charAt(0).toLowerCase() + p.slice(1);
}

export function swiftEnum(name: string, cases: { name: string; raw: string }[]): string {
    const lines = cases.map((c) => `    case ${c.name} = "${c.raw}"`);
    return [
        `enum ${name}: String, Codable, Sendable, CaseIterable {`,
        ...lines,
        "}",
        "",
    ].join("\n");
}
