export function swiftHeader(): string {
    return [
        "// Generated by native/scripts/codegen — DO NOT EDIT BY HAND.",
        "// Source of truth: packages/shared. Regenerate via `bun native/scripts/codegen/generate.ts`.",
        "",
        "",
    ].join("\n");
}

export function pascalCase(s: string): string {
    return s
        .split(/[:_\-\s]+/)
        .filter(Boolean)
        .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
        .join("");
}

export function camelCase(s: string): string {
    const p = pascalCase(s);
    return p.charAt(0).toLowerCase() + p.slice(1);
}

export function swiftEnum(name: string, cases: { name: string; raw: string }[]): string {
    const lines = cases.map((c) => `    case ${c.name} = "${c.raw}"`);
    return [
        `enum ${name}: String, Codable, Sendable, CaseIterable {`,
        ...lines,
        "}",
        "",
    ].join("\n");
}
